name: Build plugin

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # for spotless
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run spotless check
        run: ./gradlew spotlessCheck
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Cache plugin jar
        uses: actions/upload-artifact@v4
        with:
          retention-days: 7
          name: plugin
          path: build/libs/*.jar
