name: Build plugin

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      - name: Run build
        run: ./gradlew build
      - name: Cache plugin jar
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: plugin
          path: build/libs/*.jar
  run-spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # for spotless
        with:
          ref: master
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      - name: Run spotless check
        run: ./gradlew spotlessCheck